name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.1' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_USER: ubuntu
          EC2_HOST: your-ec2-public-ip
        run: |
          ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" $EC2_USER@$EC2_HOST << 'EOF'
            cd /path/to/backend
            git pull origin main
            npm install
            pm2 restart all # or start your backend server
          EOF
