name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2
      run: |  # Multi-line string for complex commands
        ssh-keygen -b 2048 -t rsa -f /tmp/private_key -N ''  # Generate a temporary SSH key (less secure)
        chmod 600 /tmp/private_key  # Set proper permissions

        # Replace <YOUR_EC2_PUBLIC_IP> with the actual public IP of your EC2 instance
        scp -o StrictHostKeyChecking=no /tmp/private_key ubuntu@175.41.212.54:/tmp/private_key.pem

        ssh -o StrictHostKeyChecking=no ubuntu@<YOUR_EC2_PUBLIC_IP> << 'EOF'  # Indent the commands for proper parsing
          cd /home/ubuntu/HMS
          git pull
          npm install
          pm2 restart HMS

          # Create .env file and set values (consider using environment variables on the server)
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "ADMIN_KEY=${{ secrets.ADMIN_KEY }}" >> .env
          # ... (repeat for other secrets)

          # Restart application
          pm2 restart HMS
        EOF

        rm /tmp/private_key /tmp/private_key.pem  # Remove temporary key pair (more secure)
      env:
        PORT: ${{ secrets.PORT }}
        ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
        # ... (define other secrets)
