name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2
      run: |
        ssh-keygen -b 2048 -t rsa -f /tmp/private_key -N ''  # Generate a temporary SSH key (less secure)
        chmod 600 /tmp/private_key  # Set proper permissions
        scp -o StrictHostKeyChecking=no /tmp/private_key ubuntu@<YOUR_EC2_PUBLIC_IP>:/tmp/private_key.pem  # Copy key to server
        ssh -o StrictHostKeyChecking=no ubuntu@<YOUR_EC2_PUBLIC_IP> << 'EOF'  # Indent the commands for proper parsing
          cd /home/ubuntu/HMS
          git pull
          npm install
          pm2 restart HMS

          # Create .env file and set values (consider using environment variables on the server)
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "ADMIN_KEY=${{ secrets.ADMIN_KEY }}" >> .env
          echo "USER_KEY=${{ secrets.USER_KEY }}" >> .env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "SMTP_MAIL=${{ secrets.SMTP_MAIL }}" >> .env
          echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> .env
          echo "MYSQL_ADDON_DB=${{ secrets.MYSQL_ADDON_DB }}" >> .env
          echo "MYSQL_ADDON_USER=${{ secrets.MYSQL_ADDON_USER }}" >> .env
          echo "MYSQL_ADDON_PASSWORD=${{ secrets.MYSQL_ADDON_PASSWORD }}" >> .env
          echo "MYSQL_ADDON_HOST=${{ secrets.MYSQL_ADDON_HOST }}" >> .env

          # Restart application
          pm2 restart HMS
        EOF
        rm /tmp/private_key /tmp/private_key.pem  # Remove temporary key pair (more secure)
      env:
        PORT: ${{ secrets.PORT }}
        ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
        USER_KEY: ${{ secrets.USER_KEY }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_MAIL: ${{ secrets.SMTP_MAIL }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
        MYSQL_ADDON_DB: ${{ secrets.MYSQL_ADDON_DB }}
        MYSQL_ADDON_USER: ${{ secrets.MYSQL_ADDON_USER }}
        MYSQL_ADDON_PASSWORD: ${{ secrets.MYSQL_ADDON_PASSWORD }}
        MYSQL_ADDON_HOST: ${{ secrets.MYSQL_ADDON_HOST }}
