name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate SSH Key
        run: |
          ssh-keygen -b 2048 -t rsa -f /tmp/private_key -N ''
          chmod 600 /tmp/private_key
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

      - name: Add SSH Key to EC2 Instance
        run: |
          PUB_KEY_CONTENT="$(cat /tmp/private_key.pub)"
          ssh -o StrictHostKeyChecking=no -i /tmp/private_key ubuntu@${{ secrets.EC2_PUBLIC_IP }} "echo '$PUB_KEY_CONTENT' >> ~/.ssh/authorized_keys"
          ssh -o StrictHostKeyChecking=no -i /tmp/private_key ubuntu@${{ secrets.EC2_PUBLIC_IP }} "chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/private_key ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ubuntu/HMS
            git pull
            npm install

            # Create .env file and set values
            echo "PORT=${{ secrets.PORT }}" > .env
            echo "ADMIN_KEY=${{ secrets.ADMIN_KEY }}" >> .env
            echo "USER_KEY=${{ secrets.USER_KEY }}" >> .env
            echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
            echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
            echo "SMTP_MAIL=${{ secrets.SMTP_MAIL }}" >> .env
            echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> .env
            echo "MYSQL_ADDON_DB=${{ secrets.MYSQL_ADDON_DB }}" >> .env
            echo "MYSQL_ADDON_USER=${{ secrets.MYSQL_ADDON_USER }}" >> .env
            echo "MYSQL_ADDON_PASSWORD=${{ secrets.MYSQL_ADDON_PASSWORD }}" >> .env
            echo "MYSQL_ADDON_HOST=${{ secrets.MYSQL_ADDON_HOST }}" >> .env

            pm2 restart HMS
          EOF
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

      - name: Clean Up SSH Key
        run: rm /tmp/private_key /tmp/private_key.pub
